sudo: required
services:
        - docker
before_script:
        - docker pull susankoju/travis-messageall || true
script: 
        - docker build --pull --cache-from susankoju/travis-messageall -t susankoju/tarvis-messageall .
        - docker run susankoju/travis-messageall

after_script:
        - docker images
before_deploy:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
        provider: script
        script: docker push susankoju/travis-messageall
        on:
                branch: master
