sudo: true
language: node_js
node_js:
        - "stable"
git:
        quest: true
cache:
        directories:
                - node_modules
script:
        
        - npm run build
deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        on:
                branch: master


